access_token = 'cc824a99-1a6f-4224-b92a-c5982b948b95'
device_id = 'f300ff2b-41bb-4c4b-94bd-33dcbc021261'
license_key = '73vjD1n0-U4Mf15P6-hn79rN54'
private_key = 'GKYIwLWV8oVjLSyCX5msUyJofdauTZ65b4OA1FKc+nk='
